### ISSUE TITLE
Bookmarklet link gives "Not found"

### ISSUE THREAD

**Issue by estan** [mislav/rfc#20]
I tried clicking the "Bookmarklet: Prettify RFC" link on the front page, but it gives a

```
Not found

Resource is not present in the app.
← Home
```

response.

**Comment by estan** [comment]
My goal is I want to try the tool out for a recent Internet Draft (draft-oberstet-hybi-tavendo-wamp) which is available at http://datatracker.ietf.org . Is there some other way except using the bookmarklet?

**Comment by estan** [comment]
I get the same error if I drag the bookmarklet to the Bookmarks Toolbar in my Firefox and then click the bookmark when showing the http://datatracker.ietf.org page for the draft.

**Comment by estan** [comment]
I realized now that the bookmarklet works when visiting e.g. http://datatracker.ietf.org/doc/rfc2616/ . Is there a way to make it work for Internet Drafts? The [second comment](https://github.com/mislav/rfc/issues/11#issuecomment-5926714) on #11 made me believe it should be possible?

**Comment by mislav** [comment]
I'm not sure what the current support for Internet Drafts is. It might not work. I'll have to look into this. Thanks for reporting!

**Comment by estan** [comment]
No problem. Would be great if it could be made to work. The draft in question (http://datatracker.ietf.org/doc/draft-oberstet-hybi-tavendo-wamp/) does have the XML source available. Thanks for a nice tool.

**Comment by estan** [comment]
I'll close this now, as there's already #11.
